# Use the latest Docker image for the CI environment
image: docker:latest

# Enable Docker-in-Docker service for building and running Docker images
services:
  - docker:dind

# Set environment variables for Docker
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

# Define the pipeline stages
stages:
  - build
  - push
  - pull
  - run

# Build stage: Build the Docker image
build:
  stage: build
  script:
    - echo "Building Docker image for Boardify..."
    - docker build -t chintanboghara/boardify:latest .

# Push stage: Log in to Docker Hub and push the image
push:
  stage: push
  script:
    - echo "Logging into Docker Hub..."
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - echo "Pushing Docker image..."
    - docker push chintanboghara/boardify:latest

# Pull stage: Pull the image to verify it's available on Docker Hub
pull:
  stage: pull
  script:
    - echo "Pulling Docker image to verify push..."
    - docker pull chintanboghara/boardify:latest

# Run stage: Run the Docker container in detached mode
run:
  stage: run
  script:
    - echo "Running Docker container for Boardify..."
    - docker run --rm -d -p 5173:5173 chintanboghara/boardify:latest
