version: "3.8"

services:
  boardify:
    # Build configuration for the Boardify service
    build:
      context: .
      dockerfile: Dockerfile
    # Map container port 80 to host port 5173
    ports:
      - "5173:80"