version: "3.8"

services:
  boardify:
    # Build configuration for the Boardify service
    build:
      context: .
      dockerfile: Dockerfile
    # Map container port 5173 to host port 5173
    ports:
      - "5173:5173"
    # Environment variables for the container
    environment:
      - NODE_ENV=development
