name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Docker Buildx for advanced build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image and tag it as latest
      - name: Build Docker Image
        run: |
          docker build -t chintanboghara/boardify:latest .

      # Log in to Docker Hub using secrets from repository settings
      - name: Docker Login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Push the built image to Docker Hub
      - name: Push Docker Image
        run: docker push chintanboghara/boardify:latest
